
package C_Home;

import Database.User;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Home extends javax.swing.JFrame {
    private Stack<User> userList;
    private int rek;
    
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
    }
    
    public Home(JFrame x, Stack<User> userList, long rek){
        x.dispose();
        super.setTitle("DNS - Home");
        this.userList = userList;
        this.rek = Integer.valueOf(rek%100 + "");
        
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
        initialize();
    }
    
    private void initialize() {
        User user = userList.get(this.rek);
        lblNama.setText(user.getNama() + "!");
        txtNama.setText(user.getNama());
        txtRek.setText(user.getNoRek() + "");
        txtJenis.setText(user.isJenisRek()? "Dewasa":"Kreatif");
                
        formatNum(txtSaldo);
        
        setLocationRelativeTo(null);
        jam();
    }
    
    private void jam(){
        time.setHorizontalAlignment(JLabel.RIGHT);
        tickTock();
        
        Timer timers = new Timer();
        TimerTask tt = new TimerTask(){
            @Override
            public void run() {
                tickTock();
            }
        };
        timers.scheduleAtFixedRate(tt, 1, 1000);
    }
    private void tickTock() {
        time.setText(new SimpleDateFormat("E, d MMM y, HH:mm:ss ").format(new Date()));
    }
    
    private void formatNum(JTextField x) {
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        x.setText(nf.format(userList.get(this.rek).getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnIsi = new javax.swing.JButton();
        btnTF = new javax.swing.JButton();
        btnMutasi = new javax.swing.JButton();
        btnInbox = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRek = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        time = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 400));
        setPreferredSize(new java.awt.Dimension(435, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(64, 176, 145));
        jPanel1.setPreferredSize(new java.awt.Dimension(110, 460));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("IEC symbols Unicode", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("⏻");
        jLabel6.setIconTextGap(0);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(19, 22, 80, 20);

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("Log     ut ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(10, 20, 90, 22);

        jPanel4.setBackground(new java.awt.Color(64, 176, 145));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1, 0, 20));

        btnIsi.setBackground(new java.awt.Color(102, 255, 204));
        btnIsi.setText("Top Up");
        btnIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiActionPerformed(evt);
            }
        });
        jPanel4.add(btnIsi);

        btnTF.setBackground(new java.awt.Color(102, 255, 204));
        btnTF.setText("Transfer");
        btnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTFActionPerformed(evt);
            }
        });
        jPanel4.add(btnTF);

        btnMutasi.setBackground(new java.awt.Color(102, 255, 204));
        btnMutasi.setText("Mutasi");
        btnMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutasiActionPerformed(evt);
            }
        });
        jPanel4.add(btnMutasi);

        btnInbox.setBackground(new java.awt.Color(102, 255, 204));
        btnInbox.setText("Ganti PIN");
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });
        jPanel4.add(btnInbox);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 150, 90, 170);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(6, 70, 100, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 110, 370);

        jPanel2.setBackground(new java.awt.Color(187, 225, 222));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 10, 300, 60);

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNama.setText("Null");
        lblNama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblNama);
        lblNama.setBounds(0, 60, 300, 50);

        jPanel3.setBackground(new java.awt.Color(187, 225, 222));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(4, 2, 5, 15));

        jLabel1.setText("Nama");
        jPanel3.add(jLabel1);

        txtNama.setEditable(false);
        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNama);

        jLabel3.setText("No. Rekening");
        jPanel3.add(jLabel3);

        txtRek.setEditable(false);
        txtRek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtRek);

        jLabel4.setText("Jenis Rekening");
        jPanel3.add(jLabel4);

        txtJenis.setEditable(false);
        txtJenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtJenis);

        jLabel5.setText("Sisa Saldo");
        jPanel3.add(jLabel5);

        txtSaldo.setEditable(false);
        txtSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtSaldo);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 140, 280, 180);

        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time.setText("jLabel6");
        jPanel2.add(time);
        time.setBounds(135, 340, 160, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(116, 0, 300, 460);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Asd kel (7).png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 420, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if(i == 0)
            new A_Opening.Opening(this, userList).setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTFActionPerformed
        new D_Transfer.Transfer(this, userList, userList.get(this.rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnTFActionPerformed

    private void btnIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiActionPerformed
        new D_IsiSaldo.IsiSaldo(this, userList, userList.get(this.rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnIsiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        formatNum(txtSaldo);
    }//GEN-LAST:event_formWindowActivated

    private void btnMutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutasiActionPerformed
        new D_Mutasi.MutasiForm(this, userList, userList.get(rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnMutasiActionPerformed

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        new X_GantiPIN.GantiPIN(this, userList, userList.get(this.rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnInboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInbox;
    private javax.swing.JButton btnIsi;
    private javax.swing.JButton btnMutasi;
    private javax.swing.JButton btnTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNama;
    private javax.swing.JButton logout;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtRek;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
