package D_Transfer;

import Database.Mutasi;
import Database.User;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Transfer extends javax.swing.JFrame {
    private JFrame x;
    private Stack<User> userList;
    private int rek;
    private Stack<String> PIN = new Stack<>();
    private boolean visibleAST = true;
    
    public Transfer() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
    }
    
    public Transfer(JFrame x, Stack<User> userList, long rek){
        this.x = x;
        this.x.dispose();
        super.setTitle("DNS - Transfer");
        this.userList = userList;
        this.rek = Integer.valueOf("" + rek%100);
        
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
        lblRek.setText(" " + userList.get(this.rek).getNoRek());
        
        setLocationRelativeTo(null);
        jam();
    }
    
    private void jam(){
        time.setHorizontalAlignment(JLabel.RIGHT);
        tickTock();
        
        Timer timers = new Timer();
        TimerTask tt = new TimerTask(){
            @Override
            public void run() {
                tickTock();
            }
        };
        timers.scheduleAtFixedRate(tt, 1, 1000);
    }
    private void tickTock() {
        time.setText(new SimpleDateFormat("E, d MMM y, HH:mm:ss ").format(new Date()));
    }
    
    private Stack<String> verify(){
        Stack<String> message = new Stack<>();
        
        String text = txtRek.getText().trim();
        int rek = Pattern.compile("^\\d\\d$").matcher(text).find()? Integer.valueOf(text):-1;
        User user = rek >= 0 && rek < userList.size()? userList.get(rek):null;
        String uang = txtUang.getText();
        double saldo = Pattern.compile("^(\\d*\\.)?\\d+$").matcher(uang).find()? Double.parseDouble(uang):-1;
        
        if(user == null)
            message.add("Rekening tujuan tidak ada");
        if(rek == this.rek)
            message.add("Tidak bisa mentransfer ke diri sendiri");
        if(saldo > userList.get(this.rek).getSaldo())
            message.add("Saldo di akun Anda kurang mencukupi");
        if(saldo <= 0)
            message.add("Jumlah Transfer harus positif");
        
        message.add(message.isEmpty()? null:"Y");
        
        return message;
    }
    
    private String ast(){
        if(visibleAST)
            return String.join("", PIN);
        return "*".repeat(PIN.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnIsi = new javax.swing.JButton();
        btnTF = new javax.swing.JButton();
        btnMutasi = new javax.swing.JButton();
        btnInbox = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBackFrame1 = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        txtPesan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblRek = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRek = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        namaTujuan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAngka = new javax.swing.JTextField();
        btn9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        PINVisibility = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lupaPIN = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 400));
        setResizable(false);

        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(64, 176, 145));
        jPanel4.setPreferredSize(new java.awt.Dimension(110, 460));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(64, 176, 145));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1, 0, 20));

        btnIsi.setBackground(new java.awt.Color(102, 255, 204));
        btnIsi.setText("Top Up");
        btnIsi.setEnabled(false);
        btnIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiActionPerformed(evt);
            }
        });
        jPanel5.add(btnIsi);

        btnTF.setBackground(new java.awt.Color(102, 255, 204));
        btnTF.setText("Transfer");
        btnTF.setEnabled(false);
        btnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTFActionPerformed(evt);
            }
        });
        jPanel5.add(btnTF);

        btnMutasi.setBackground(new java.awt.Color(102, 255, 204));
        btnMutasi.setText("Mutasi");
        btnMutasi.setEnabled(false);
        btnMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutasiActionPerformed(evt);
            }
        });
        jPanel5.add(btnMutasi);

        btnInbox.setBackground(new java.awt.Color(102, 255, 204));
        btnInbox.setText("Ganti PIN");
        btnInbox.setEnabled(false);
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });
        jPanel5.add(btnInbox);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 150, 90, 170);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Logo.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(6, 70, 100, 60);

        btnBackFrame1.setBackground(new java.awt.Color(221, 240, 255));
        btnBackFrame1.setText("❮");
        btnBackFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFrame1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBackFrame1);
        btnBackFrame1.setBounds(10, 20, 90, 22);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 110, 360);

        tabPane.setBackground(new java.awt.Color(221, 240, 255));
        tabPane.setEnabled(false);

        jPanel1.setOpaque(false);

        jLabel3.setText("Jumlah Uang");

        txtUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangActionPerformed(evt);
            }
        });
        txtUang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUangKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUangKeyTyped(evt);
            }
        });

        jLabel4.setText("Pesan (Berita)");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblRek.setText(" ");

        jLabel1.setText("Dari Rekening ");

        jLabel2.setText("Rekening Tujuan");

        txtRek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRekFocusLost(evt);
            }
        });
        txtRek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRekActionPerformed(evt);
            }
        });
        txtRek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRekKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRekKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRekKeyTyped(evt);
            }
        });

        jLabel6.setText("Nama Tujuan");

        namaTujuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRek)
                            .addComponent(lblRek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNext)
                            .addComponent(namaTujuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesan)
                            .addComponent(txtUang))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(lblRek, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaTujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(20, 20, 20))
        );

        tabPane.addTab("Detail", jPanel1);

        jPanel2.setOpaque(false);

        txtAngka.setEditable(false);
        txtAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngkaActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel5.setText("Masukkan PIN");

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnEnter.setText("CONFIRM");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnBackspace.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnBackspace.setText("BACKSPACE");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        PINVisibility.setText("👁");
        PINVisibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINVisibilityActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setText("❮");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lupaPIN.setForeground(new java.awt.Color(0, 204, 255));
        lupaPIN.setText("Lupa PIN?");
        lupaPIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lupaPINFocusGained(evt);
            }
        });
        lupaPIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaPINMouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("________");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lupaPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PINVisibility, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PINVisibility, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lupaPIN))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabPane.addTab("Konfirmasi", jPanel2);

        jPanel3.add(tabPane);
        tabPane.setBounds(110, 0, 310, 320);

        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time.setText("jLabel5");
        jPanel3.add(time);
        time.setBounds(230, 340, 185, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Asd kel (7).png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 0, 420, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangActionPerformed
        
    }//GEN-LAST:event_txtUangActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        Stack<String> cek = verify();
        
        if(cek.pop() != null)
            JOptionPane.showMessageDialog(this, String.join("\n", cek), "Warning", 2);
        else if(txtPesan.getText().trim().isEmpty()){
            int i = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Tidak Ingin Menambahkan Pesan?", "Pesan Kosong", JOptionPane.YES_NO_OPTION);
            if(i == 0) tabPane.setSelectedIndex(1);
        }
        else
            tabPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngkaActionPerformed

    }//GEN-LAST:event_txtAngkaActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn9.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        PIN.clear();
        txtAngka.setText(String.join("", PIN));
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn3.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn0.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        if(!userList.get(rek).cekPIN(txtAngka.getText())){
            JOptionPane.showMessageDialog(this, "PIN yang Dimasukkan Salah", "Warning", 2);
        }
        else{
            int tujuan = Integer.valueOf(txtRek.getText());
            double total = Double.parseDouble("0" + txtUang.getText());
            Date waktu = new Date();
            
            userList.get(tujuan).addSaldo(total);
            userList.get(tujuan).addMutasi(new Mutasi(waktu, userList.get(tujuan), userList.get(this.rek), total, txtPesan.getText(), true));
            userList.get(this.rek).addSaldo(- Double.parseDouble(txtUang.getText()));
            userList.get(this.rek).addMutasi(new Mutasi(waktu, userList.get(this.rek), userList.get(tujuan), total, txtPesan.getText(), false));
            
            
            JOptionPane.showMessageDialog(this, "Transfer Berhasil!", "Berhasil", 1);
            
            this.dispose();
            this.x.setVisible(true);
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn2.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn4.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        PIN.pop();
        txtAngka.setText(ast());
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn1.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn1ActionPerformed

    private void PINVisibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINVisibilityActionPerformed
        visibleAST = !visibleAST;
        txtAngka.setText(ast());
    }//GEN-LAST:event_PINVisibilityActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn5.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn6.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here
        PIN.push(btn7.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        PIN.push(btn8.getText());

        txtAngka.setText(ast());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        tabPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiActionPerformed
        new D_IsiSaldo.IsiSaldo(this, userList, userList.get(this.rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnIsiActionPerformed

    private void btnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTFActionPerformed
        new D_Transfer.Transfer(this, userList, this.rek).setVisible(true);
    }//GEN-LAST:event_btnTFActionPerformed

    private void btnMutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutasiActionPerformed
        new D_Mutasi.MutasiForm(this, userList, userList.get(rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnMutasiActionPerformed

    private void btnBackFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFrame1ActionPerformed
        this.x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackFrame1ActionPerformed

    private void txtRekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRekActionPerformed
        
    }//GEN-LAST:event_txtRekActionPerformed

    private void txtRekFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRekFocusLost
        
    }//GEN-LAST:event_txtRekFocusLost

    private void txtRekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRekKeyTyped
        
    }//GEN-LAST:event_txtRekKeyTyped

    private void txtUangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangKeyTyped
        
    }//GEN-LAST:event_txtUangKeyTyped

    private void txtUangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangKeyPressed
       
    }//GEN-LAST:event_txtUangKeyPressed

    private void txtRekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRekKeyPressed
        
    }//GEN-LAST:event_txtRekKeyPressed

    private void txtRekKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRekKeyReleased
        if(Pattern.compile("^\\d\\d$").matcher(txtRek.getText().trim()).find()){
            int rek = Integer.valueOf(txtRek.getText());
            if(rek < userList.size()){
                namaTujuan.setForeground(Color.white);
                namaTujuan.setText(" " + userList.get(rek).getNama() + " - " + userList.get(rek).getNoRek());
            }
            else {
                namaTujuan.setForeground(Color.red);
                namaTujuan.setText(" Tidak Terdaftar");
            }
        }
        else{
            namaTujuan.setForeground(Color.red);
            namaTujuan.setText(" Tidak Terdaftar");
        }
    }//GEN-LAST:event_txtRekKeyReleased

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        new X_GantiPIN.GantiPIN(this, userList, userList.get(this.rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnInboxActionPerformed

    private void lupaPINFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lupaPINFocusGained

    }//GEN-LAST:event_lupaPINFocusGained

    private void lupaPINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaPINMouseClicked
        new X_GantiPIN.GantiPIN(this, userList, userList.get(rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_lupaPINMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PINVisibility;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackFrame1;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnInbox;
    private javax.swing.JButton btnIsi;
    private javax.swing.JButton btnMutasi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblRek;
    private javax.swing.JLabel lupaPIN;
    private javax.swing.JLabel namaTujuan;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtAngka;
    private javax.swing.JTextField txtPesan;
    private javax.swing.JTextField txtRek;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
