package B_Login;

import Database.User;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    private Stack<String> PIN = new Stack<>();
    private boolean visibleAST = true;
    private Stack<User> userList;
    private JFrame x;
    
    public Login() {
        initialize();
    }
    
    public Login(JFrame x, Stack<User> userList) {
        this.x = x;
        this.x.dispose();
        this.userList = userList;
        
        initialize();
    }
    
    private void initialize(){
        super.setTitle("DNS Login");
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
        
        txtAngka.setToolTipText("Ketik/Gunakan Tombol PIN");
        txtRek.setToolTipText("2 Digit Terakhir No Rek");
        PINVisibility.setToolTipText("Sembunyikan/Tampilkan PIN");
        dropDown.setToolTipText("Tampilkan Tombol PIN");
        
        setLocationRelativeTo(null);
        jam();
    }
    
    private void jam(){
        time.setHorizontalAlignment(JLabel.RIGHT);
        tickTock();
        
        Timer timers = new Timer();
        TimerTask tt = new TimerTask(){
            @Override
            public void run() {
                tickTock();
            }
        };
        timers.scheduleAtFixedRate(tt, 1, 1000);
    }
    private void tickTock() {
        time.setText(new SimpleDateFormat("E, d MMM y, HH:mm:ss ").format(new Date()));
    }
    
    private String ast(){
        if(visibleAST)
            return String.join("", PIN);
            
        return "*".repeat(PIN.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtAngka = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        PINVisibility = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        dropDown = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        txtRek = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lupaPIN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBackFrame = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBackspace = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 200));
        setPreferredSize(new java.awt.Dimension(435, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        txtAngka.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtAngkaComponentAdded(evt);
            }
        });
        txtAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngkaActionPerformed(evt);
            }
        });
        txtAngka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAngkaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAngkaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAngkaKeyTyped(evt);
            }
        });
        jPanel1.add(txtAngka);
        txtAngka.setBounds(50, 110, 238, 33);

        jLabel2.setText("Masukkan PIN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 150, 16);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(140, 160, 53, 41);

        PINVisibility.setText("👁");
        PINVisibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINVisibilityActionPerformed(evt);
            }
        });
        jPanel1.add(PINVisibility);
        PINVisibility.setBounds(300, 110, 46, 33);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(210, 160, 53, 41);

        dropDown.setText("-");
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });
        jPanel1.add(dropDown);
        dropDown.setBounds(350, 110, 41, 33);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(70, 210, 53, 41);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(140, 210, 53, 41);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(210, 210, 53, 41);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);
        btn7.setBounds(70, 260, 53, 41);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(140, 260, 53, 41);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);
        btn9.setBounds(210, 260, 53, 41);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);
        btn0.setBounds(140, 310, 53, 41);

        txtRek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRekActionPerformed(evt);
            }
        });
        jPanel1.add(txtRek);
        txtRek.setBounds(50, 40, 341, 30);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(70, 160, 53, 41);

        jLabel1.setText("2 Digit Terakhir Nomor Rekening");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 220, 16);

        lupaPIN.setForeground(new java.awt.Color(0, 204, 255));
        lupaPIN.setText("Lupa PIN?");
        lupaPIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lupaPINFocusGained(evt);
            }
        });
        lupaPIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaPINMouseClicked(evt);
            }
        });
        jPanel1.add(lupaPIN);
        lupaPIN.setBounds(320, 90, 70, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("❮");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 30);

        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("________");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 90, 70, 16);

        btnBackFrame.setBackground(new java.awt.Color(221, 240, 255));
        btnBackFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFrameActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackFrame);
        btnBackFrame.setBounds(10, 10, 30, 30);

        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(time);
        time.setBounds(250, 10, 160, 20);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        btnBackspace.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnBackspace.setText("BACKSPACE");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });
        jPanel2.add(btnBackspace);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);

        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnter);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 160, 100, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Asd kel (7).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 420, 360);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngkaActionPerformed
        
    }//GEN-LAST:event_txtAngkaActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        PIN.push(btn1.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        PIN.push(btn2.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        PIN.push(btn3.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        PIN.push(btn4.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        PIN.push(btn5.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        PIN.push(btn6.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        PIN.push(btn7.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        PIN.push(btn8.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        PIN.push(btn9.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        PIN.push(btn0.getText());
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        PIN.pop();
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        PIN.clear();
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        String text = txtRek.getText().trim();
        int rek = Pattern.compile("^\\d\\d$").matcher(text).find()? Integer.valueOf(text):-1;
        User user = rek >= 0 && rek < userList.size()? userList.get(rek):null;
        
        if(user == null)
            JOptionPane.showMessageDialog(this, "Rekening tidak ada", "Warning", 1, null);
        else{
            if(user.cekPIN(String.join("", PIN)))
                new C_Home.Home(this, userList, user.getNoRek()).setVisible(true);
            else
                JOptionPane.showMessageDialog(this, "PIN yang anda masukkan salah", "Warning", 1, null);
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void txtRekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRekActionPerformed
        
    }//GEN-LAST:event_txtRekActionPerformed

    private void PINVisibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINVisibilityActionPerformed
        visibleAST = !visibleAST;
        txtAngka.setText(ast());
    }//GEN-LAST:event_PINVisibilityActionPerformed
    
    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        if(dropDown.getText().equals("⏎"))
            btnEnterActionPerformed(evt);
        else if(!dropDown.getText().equals("▲")){
            setSize(new Dimension(435, 400));
            dropDown.setText("▲");
            txtAngka.setEditable(false);
        }
        else{
            setSize(new Dimension(435, 200));
            dropDown.setText("▼");
            txtAngka.setEditable(false);
        }
        
    
    }//GEN-LAST:event_dropDownActionPerformed

    private void lupaPINFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lupaPINFocusGained
        
    }//GEN-LAST:event_lupaPINFocusGained

    private void lupaPINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaPINMouseClicked
        new X_GantiPIN.LupaPIN(this, userList).setVisible(true);
    }//GEN-LAST:event_lupaPINMouseClicked

    private void btnBackFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFrameActionPerformed
        this.x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackFrameActionPerformed

    private void txtAngkaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngkaKeyPressed
        
    }//GEN-LAST:event_txtAngkaKeyPressed

    private void txtAngkaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtAngkaComponentAdded
        
    }//GEN-LAST:event_txtAngkaComponentAdded

    private void txtAngkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngkaKeyTyped
        
    }//GEN-LAST:event_txtAngkaKeyTyped

    private void txtAngkaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngkaKeyReleased
        String key = evt.getKeyChar() + "";
        
        if((evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) && !PIN.isEmpty() && txtAngka.isEditable()){
            PIN.pop();
        }
        else if(Pattern.compile("\\d").matcher(key).find() && "-⏎".contains(dropDown.getText())){
            dropDown.setText("⏎");
            dropDown.setToolTipText("Enter");
            PIN.push(key);
        }
        
        txtAngka.setText(ast());
    }//GEN-LAST:event_txtAngkaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PINVisibility;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBackFrame;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton dropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lupaPIN;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtAngka;
    private javax.swing.JTextField txtRek;
    // End of variables declaration//GEN-END:variables
}
