
package X_GantiPIN;

import Database.User;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class GantiPIN extends javax.swing.JFrame {
    private Stack<User> userList;
    private JFrame x;
    private int rek;
    
    public GantiPIN() {
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
    }
    
    public GantiPIN(JFrame x, Stack<User> userList, long rek) {
        this.x = x;
        this.x.dispose();
        super.setTitle("DNS - Ganti PIN");
        this.userList = userList;
        this.rek = Integer.valueOf("" + rek%100);
        
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
        
        setLocationRelativeTo(null);
        jam();
        
    }
    
    private void jam(){
        time.setHorizontalAlignment(JLabel.RIGHT);
        tickTock();
        
        Timer timers = new Timer();
        TimerTask tt = new TimerTask(){
            @Override
            public void run() {
                tickTock();
            }
        };
        timers.scheduleAtFixedRate(tt, 1, 1000);
    }
    private void tickTock() {
        time.setText(new SimpleDateFormat("E, d MMM y, HH:mm:ss ").format(new Date()));
    }
    
    private Stack<String> verify1(){        
        Stack<String> message = new Stack<>();
        User user = userList.get(rek);
        
        if(!(user.cekPIN(txtPIN.getText().trim()) || user.cekIbu(txtIbu.getText())))
            message.add("Salah Satu Field Harus Diisi dengan Benar");
        if(!Pattern.compile("^\\d{6}$").matcher(PINBaru.getText().trim()).find())
            message.add("PIN Hanya Boleh Mengandung Angka dan Sepanjang 6 Digit");
        
        message.add(message.isEmpty()? null:"Y");
        
        return message;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnIsi = new javax.swing.JButton();
        btnTF = new javax.swing.JButton();
        btnMutasi = new javax.swing.JButton();
        btnInbox = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBackFrame = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtPIN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PINBaru = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIbu = new javax.swing.JTextField();
        btnKonf = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 400));
        setPreferredSize(new java.awt.Dimension(435, 400));

        jPanel1.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(64, 176, 145));
        jPanel5.setPreferredSize(new java.awt.Dimension(110, 460));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(64, 176, 145));
        jPanel6.setLayout(new java.awt.GridLayout(4, 1, 0, 20));

        btnIsi.setBackground(new java.awt.Color(102, 255, 204));
        btnIsi.setText("Top Up");
        btnIsi.setEnabled(false);
        btnIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiActionPerformed(evt);
            }
        });
        jPanel6.add(btnIsi);

        btnTF.setBackground(new java.awt.Color(102, 255, 204));
        btnTF.setText("Transfer");
        btnTF.setEnabled(false);
        btnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTFActionPerformed(evt);
            }
        });
        jPanel6.add(btnTF);

        btnMutasi.setBackground(new java.awt.Color(102, 255, 204));
        btnMutasi.setText("Mutasi");
        btnMutasi.setEnabled(false);
        btnMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutasiActionPerformed(evt);
            }
        });
        jPanel6.add(btnMutasi);

        btnInbox.setBackground(new java.awt.Color(102, 255, 204));
        btnInbox.setText("Ganti PIN");
        btnInbox.setEnabled(false);
        jPanel6.add(btnInbox);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 150, 90, 170);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Logo.png"))); // NOI18N
        jPanel5.add(jLabel7);
        jLabel7.setBounds(6, 70, 100, 60);

        btnBackFrame.setBackground(new java.awt.Color(221, 240, 255));
        btnBackFrame.setText("❮");
        btnBackFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFrameActionPerformed(evt);
            }
        });
        jPanel5.add(btnBackFrame);
        btnBackFrame.setBounds(10, 20, 90, 22);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 110, 360);

        jPanel2.setLayout(null);
        jPanel2.add(txtPIN);
        txtPIN.setBounds(130, 160, 270, 30);

        jLabel3.setText("Atau");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 100, 25, 16);

        jLabel6.setText("Masukkan PIN Baru Anda");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(130, 230, 270, 16);

        PINBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINBaruActionPerformed(evt);
            }
        });
        jPanel2.add(PINBaru);
        PINBaru.setBounds(130, 250, 270, 30);

        jLabel1.setText("Masukkan Nama Ibu Anda");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 30, 270, 16);

        jLabel8.setForeground(new java.awt.Color(221, 240, 255));
        jLabel8.setText("____________________________________________________________");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 200, 430, 16);
        jPanel2.add(txtIbu);
        txtIbu.setBounds(130, 50, 270, 30);

        btnKonf.setText("Konfirm");
        btnKonf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfActionPerformed(evt);
            }
        });
        jPanel2.add(btnKonf);
        btnKonf.setBounds(230, 302, 73, 30);

        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time.setText("jLabel8");
        jPanel2.add(time);
        time.setBounds(250, 340, 156, 16);

        jLabel2.setText("Masukkan PIN Lama Anda");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 140, 270, 16);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Asd kel (7).png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 420, 360);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFrameActionPerformed
        this.x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackFrameActionPerformed

    private void btnMutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutasiActionPerformed
        new D_Mutasi.MutasiForm(this, userList, userList.get(rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnMutasiActionPerformed

    private void btnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTFActionPerformed
        new D_Transfer.Transfer(this, userList, this.rek).setVisible(true);
    }//GEN-LAST:event_btnTFActionPerformed

    private void btnIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiActionPerformed
        new D_IsiSaldo.IsiSaldo(this, userList, userList.get(this.rek).getNoRek()).setVisible(true);
    }//GEN-LAST:event_btnIsiActionPerformed

    private void PINBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINBaruActionPerformed

    private void btnKonfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfActionPerformed
        Stack<String> cek = verify1();

        if(cek.pop() != null)
            JOptionPane.showMessageDialog(this, String.join("\n", cek), "Warning", 2);
        else{
            String baru = PINBaru.getText().trim();
            
            userList.get(rek).gantiPIN(txtPIN.getText().trim(), baru);
            userList.get(rek).gantiPIN(txtIbu.getText().trim(), baru);
            
            JOptionPane.showMessageDialog(this, "PIN Berhasil Diubah", "Berhasil", 1);
            
            new C_Home.Home(this, userList, userList.get(rek).getNoRek()).setVisible(true);
        }
    }//GEN-LAST:event_btnKonfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GantiPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GantiPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GantiPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GantiPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GantiPIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PINBaru;
    private javax.swing.JButton btnBackFrame;
    private javax.swing.JButton btnInbox;
    private javax.swing.JButton btnIsi;
    private javax.swing.JButton btnKonf;
    private javax.swing.JButton btnMutasi;
    private javax.swing.JButton btnTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtIbu;
    private javax.swing.JTextField txtPIN;
    // End of variables declaration//GEN-END:variables
}
