package X_GantiPIN;

import Database.User;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class LupaPIN extends javax.swing.JFrame {
    private Stack<User> userList;
    private JFrame x;
    
    public LupaPIN() {
        super.setTitle("DNS - Lupa PIN");
        
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
        setLocationRelativeTo(null);
    }
    
    public LupaPIN(JFrame x, Stack<User> userList) {
        this.x = x;
        this.x.dispose();
        super.setTitle("DNS - Lupa PIN");
        this.userList = userList;
        
        initComponents();
        setIconImage(new ImageIcon("C:\\Users\\steve\\Documents\\NetBeansProjects\\ASD DNS\\src\\A_Opening\\Logo.png").getImage());
        
        setLocationRelativeTo(null);
        jam();
    }
    
    private void jam(){
        time.setHorizontalAlignment(JLabel.RIGHT);
        tickTock();
        
        Timer timers = new Timer();
        TimerTask tt = new TimerTask(){
            @Override
            public void run() {
                tickTock();
            }
        };
        timers.scheduleAtFixedRate(tt, 1, 1000);
    }
    private void tickTock() {
        time.setText(new SimpleDateFormat("E, d MMM y, HH:mm:ss ").format(new Date()));
    }
    
    private Stack<String> verify1(){        
        Stack<String> message = new Stack<>();
        String text = txtRek.getText().trim();
        int rek = Pattern.compile("^\\d\\d$").matcher(text).find()? Integer.valueOf(text):-1;
        User user = rek >= 0 && rek < userList.size()? userList.get(rek):null;
        
        if(user == null)
            message.add("Rekening tidak ada");
        else{
            if(!(user.cekPIN(txtPIN.getText().trim()) || user.cekIbu(txtIbu.getText())))
                message.add("Salah Satu Field Harus Diisi dengan Benar");
            if(!Pattern.compile("^\\d{6}$").matcher(PINBaru.getText().trim()).find())
                message.add("PIN Hanya Boleh Mengandung Angka dan Sepanjang 6 Digit");
        }
        message.add(message.isEmpty()? null:"Y");
        
        return message;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPIN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PINBaru = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIbu = new javax.swing.JTextField();
        btnKonf = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBackFrame = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 400));
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(txtPIN);
        txtPIN.setBounds(50, 180, 320, 30);

        jLabel3.setText("Atau");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 140, 25, 16);

        jLabel4.setText("2 Digit Terakhir No. Rek");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 20, 320, 16);
        jPanel1.add(txtRek);
        txtRek.setBounds(50, 40, 320, 30);

        jLabel5.setForeground(new java.awt.Color(221, 240, 255));
        jLabel5.setText("____________________________________________________________");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 70, 430, 16);

        jLabel6.setText("Masukkan PIN Baru Anda");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 240, 320, 16);

        PINBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINBaruActionPerformed(evt);
            }
        });
        jPanel1.add(PINBaru);
        PINBaru.setBounds(50, 260, 320, 30);

        jLabel1.setText("Masukkan Nama Ibu Anda");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 90, 320, 16);

        jLabel7.setForeground(new java.awt.Color(221, 240, 255));
        jLabel7.setText("____________________________________________________________");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 210, 430, 16);
        jPanel1.add(txtIbu);
        txtIbu.setBounds(50, 110, 320, 30);

        btnKonf.setText("Konfirm");
        btnKonf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfActionPerformed(evt);
            }
        });
        jPanel1.add(btnKonf);
        btnKonf.setBounds(170, 310, 73, 22);

        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time.setText("jLabel8");
        jPanel1.add(time);
        time.setBounds(250, 340, 156, 16);

        jLabel2.setText("Masukkan PIN Lama Anda");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 160, 320, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("❮");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 10, 30, 30);

        btnBackFrame.setBackground(new java.awt.Color(221, 240, 255));
        btnBackFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFrameActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackFrame);
        btnBackFrame.setBounds(10, 10, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A_Opening/Asd kel (7).png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 420, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfActionPerformed
        Stack<String> cek = verify1();
        
        if(cek.pop() != null)
            JOptionPane.showMessageDialog(this, String.join("\n", cek), "Warning", 2);
        else{
            int reks = Integer.valueOf(txtRek.getText().trim());
            String baru = PINBaru.getText().trim();
            
            userList.get(reks).gantiPIN(txtPIN.getText().trim(), baru);
            userList.get(reks).gantiPIN(txtIbu.getText().trim(), baru);
            
            JOptionPane.showMessageDialog(this, "PIN Berhasil Diubah", "Berhasil", 1);
            new A_Opening.Opening(this, userList).setVisible(true);
        }
    }//GEN-LAST:event_btnKonfActionPerformed

    private void PINBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINBaruActionPerformed

    private void btnBackFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFrameActionPerformed
        this.x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PINBaru;
    private javax.swing.JButton btnBackFrame;
    private javax.swing.JButton btnKonf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtIbu;
    private javax.swing.JTextField txtPIN;
    private javax.swing.JTextField txtRek;
    // End of variables declaration//GEN-END:variables
}
